### ISSUE TITLE
Possible Logo for the Project

### ISSUE THREAD

**Issue by bordoni** [dockunit/platform#1]
Just an Idea, I just copied over the Path to change colors.
![dockunit](https://cloud.githubusercontent.com/assets/236579/8594108/4238781e-2614-11e5-87e0-edd0a87af464.png)

[The original one](http://graphicriver.net/item/hunt-tech-logo/11025750) looks a bit more polished.

**Comment by tlovett1** [comment]
@bordoni any update? If you don't have time to finish, I'm happy to takeover

**Comment by bordoni** [comment]
I didn't sorry. This last 4 days has been a bit crazy.
