### ISSUE TITLE
Branch-switcher dropdown does not correctly switch branches

### ISSUE THREAD

**Issue by johnpbloch** [dockunit/platform#3]
**Steps to reproduce**: Go to [a dockunit.io project page](https://dockunit.io/projects/10up/ElasticPress) and use the dropdown to select another branch

**Expected behavior**: URL hash will change to the name of the branch and the branch's builds will be displayed

**Actual behavior**: URL hash changes to `#undefined` and an error is displayed:

![dockunit-bug](https://cloud.githubusercontent.com/assets/446833/10253690/544e9762-6904-11e5-92dc-4d1e5f2248b7.PNG)

**Comment by tlovett1** [comment]
Maybe that's a problem with a specific branch? I can't reproduce.

**Comment by johnpbloch** [comment]
It happens for me on all branches. Browser is Firefox (latest) on Windows 10. I'll test other browsers later and get any error messages from the console later today.

**Comment by tlovett1** [comment]
Wow ok. Seeing the problem in Firefox. Thanks!

**Comment by tlovett1** [comment]
Fixed

**Comment by johnpbloch** [comment]
![giphy](https://cloud.githubusercontent.com/assets/446833/10284796/699fac02-6b4b-11e5-9724-380011725e60.gif)
